name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: ğŸ— Setup Electron
        uses: ./.github/actions/setup-electron

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ§ª Test
        run: |
          pnpm lint
          pnpm exec tsc
          pnpm test
