name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ğŸ— Setup Electron
        uses: ./.github/actions/setup-electron

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ§ª Test
        run: |
          pnpm lint
          pnpm exec tsc
          pnpm test
